namespace ECommerceApp.Migrations
{
    using System;
    using System.Data.Entity.Migrations;

    /// <summary>
    /// Initial migration - Creates all tables for the E-Commerce database.
    /// Generated by Code First Migrations.
    /// </summary>
    public partial class InitialCreate : DbMigration
    {
        public override void Up()
        {
            // Create Users table
            CreateTable(
                "dbo.Users",
                c => new
                {
                    UserID = c.Int(nullable: false, identity: true),
                    Username = c.String(nullable: false, maxLength: 50),
                    Email = c.String(nullable: false, maxLength: 100),
                    HashedPassword = c.String(nullable: false, maxLength: 256),
                    UserRole = c.String(nullable: false, maxLength: 20),
                    CreatedDate = c.DateTime(nullable: false),
                    IsActive = c.Boolean(nullable: false),
                })
                .PrimaryKey(t => t.UserID)
                .Index(t => t.Username, unique: true, name: "IX_Username");

            // Create Categories table
            CreateTable(
                "dbo.Categories",
                c => new
                {
                    CategoryID = c.Int(nullable: false, identity: true),
                    CategoryName = c.String(nullable: false, maxLength: 100),
                    Description = c.String(maxLength: 500),
                })
                .PrimaryKey(t => t.CategoryID);

            // Create Products table
            CreateTable(
                "dbo.Products",
                c => new
                {
                    ProductID = c.Int(nullable: false, identity: true),
                    ProductName = c.String(nullable: false, maxLength: 200),
                    Description = c.String(maxLength: 1000),
                    Price = c.Decimal(nullable: false, precision: 18, scale: 2),
                    CategoryID = c.Int(nullable: false),
                    StoreOwnerID = c.Int(nullable: false),
                    ImageURL = c.String(maxLength: 500),
                    CreatedDate = c.DateTime(nullable: false),
                    IsActive = c.Boolean(nullable: false),
                })
                .PrimaryKey(t => t.ProductID)
                .ForeignKey("dbo.Categories", t => t.CategoryID, cascadeDelete: false)
                .ForeignKey("dbo.Users", t => t.StoreOwnerID, cascadeDelete: false)
                .Index(t => t.CategoryID)
                .Index(t => t.StoreOwnerID);

            // Create Inventory table
            CreateTable(
                "dbo.Inventory",
                c => new
                {
                    InventoryID = c.Int(nullable: false, identity: true),
                    ProductID = c.Int(nullable: false),
                    StockQuantity = c.Int(nullable: false),
                    MinimumStock = c.Int(nullable: false),
                    LastUpdated = c.DateTime(nullable: false),
                })
                .PrimaryKey(t => t.InventoryID)
                .ForeignKey("dbo.Products", t => t.ProductID, cascadeDelete: true)
                .Index(t => t.ProductID, unique: true, name: "IX_ProductID");

            // Create Orders table
            CreateTable(
                "dbo.Orders",
                c => new
                {
                    OrderID = c.Int(nullable: false, identity: true),
                    CustomerID = c.Int(nullable: false),
                    OrderDate = c.DateTime(nullable: false),
                    OrderStatus = c.String(nullable: false, maxLength: 50),
                    TotalAmount = c.Decimal(nullable: false, precision: 18, scale: 2),
                    ShippingAddress = c.String(maxLength: 500),
                    ProcessedBy = c.Int(),
                })
                .PrimaryKey(t => t.OrderID)
                .ForeignKey("dbo.Users", t => t.CustomerID, cascadeDelete: false)
                .ForeignKey("dbo.Users", t => t.ProcessedBy)
                .Index(t => t.CustomerID)
                .Index(t => t.ProcessedBy);

            // Create OrderDetails table
            CreateTable(
                "dbo.OrderDetails",
                c => new
                {
                    OrderDetailID = c.Int(nullable: false, identity: true),
                    OrderID = c.Int(nullable: false),
                    ProductID = c.Int(nullable: false),
                    Quantity = c.Int(nullable: false),
                    UnitPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                })
                .PrimaryKey(t => t.OrderDetailID)
                .ForeignKey("dbo.Orders", t => t.OrderID, cascadeDelete: true)
                .ForeignKey("dbo.Products", t => t.ProductID, cascadeDelete: false)
                .Index(t => t.OrderID)
                .Index(t => t.ProductID);

            // Create SupportTickets table
            CreateTable(
                "dbo.SupportTickets",
                c => new
                {
                    TicketID = c.Int(nullable: false, identity: true),
                    CustomerID = c.Int(nullable: false),
                    Subject = c.String(nullable: false, maxLength: 200),
                    Description = c.String(nullable: false, maxLength: 2000),
                    Status = c.String(nullable: false, maxLength: 50),
                    Priority = c.String(nullable: false, maxLength: 20),
                    CreatedDate = c.DateTime(nullable: false),
                    AssignedToID = c.Int(),
                    ResolvedDate = c.DateTime(),
                })
                .PrimaryKey(t => t.TicketID)
                .ForeignKey("dbo.Users", t => t.CustomerID, cascadeDelete: false)
                .ForeignKey("dbo.Users", t => t.AssignedToID)
                .Index(t => t.CustomerID)
                .Index(t => t.AssignedToID);

            // Create Reviews table
            CreateTable(
                "dbo.Reviews",
                c => new
                {
                    ReviewID = c.Int(nullable: false, identity: true),
                    ProductID = c.Int(nullable: false),
                    CustomerID = c.Int(nullable: false),
                    Rating = c.Int(nullable: false),
                    Comment = c.String(maxLength: 1000),
                    ReviewDate = c.DateTime(nullable: false),
                })
                .PrimaryKey(t => t.ReviewID)
                .ForeignKey("dbo.Products", t => t.ProductID, cascadeDelete: true)
                .ForeignKey("dbo.Users", t => t.CustomerID, cascadeDelete: false)
                .Index(t => t.ProductID)
                .Index(t => t.CustomerID);
        }

        public override void Down()
        {
            // Drop foreign keys and tables in reverse order
            DropForeignKey("dbo.Reviews", "CustomerID", "dbo.Users");
            DropForeignKey("dbo.Reviews", "ProductID", "dbo.Products");
            DropForeignKey("dbo.SupportTickets", "AssignedToID", "dbo.Users");
            DropForeignKey("dbo.SupportTickets", "CustomerID", "dbo.Users");
            DropForeignKey("dbo.OrderDetails", "ProductID", "dbo.Products");
            DropForeignKey("dbo.OrderDetails", "OrderID", "dbo.Orders");
            DropForeignKey("dbo.Orders", "ProcessedBy", "dbo.Users");
            DropForeignKey("dbo.Orders", "CustomerID", "dbo.Users");
            DropForeignKey("dbo.Inventory", "ProductID", "dbo.Products");
            DropForeignKey("dbo.Products", "StoreOwnerID", "dbo.Users");
            DropForeignKey("dbo.Products", "CategoryID", "dbo.Categories");

            DropIndex("dbo.Reviews", new[] { "CustomerID" });
            DropIndex("dbo.Reviews", new[] { "ProductID" });
            DropIndex("dbo.SupportTickets", new[] { "AssignedToID" });
            DropIndex("dbo.SupportTickets", new[] { "CustomerID" });
            DropIndex("dbo.OrderDetails", new[] { "ProductID" });
            DropIndex("dbo.OrderDetails", new[] { "OrderID" });
            DropIndex("dbo.Orders", new[] { "ProcessedBy" });
            DropIndex("dbo.Orders", new[] { "CustomerID" });
            DropIndex("dbo.Inventory", "IX_ProductID");
            DropIndex("dbo.Products", new[] { "StoreOwnerID" });
            DropIndex("dbo.Products", new[] { "CategoryID" });
            DropIndex("dbo.Users", "IX_Username");

            DropTable("dbo.Reviews");
            DropTable("dbo.SupportTickets");
            DropTable("dbo.OrderDetails");
            DropTable("dbo.Orders");
            DropTable("dbo.Inventory");
            DropTable("dbo.Products");
            DropTable("dbo.Categories");
            DropTable("dbo.Users");
        }
    }
}
