using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace ECommerceApp.Models
{
    /// <summary>
    /// Entity Framework DbContext for E-Commerce database.
    /// This is generated by Entity Framework Database-First approach.
    /// </summary>
    public partial class ECommerceEntities : DbContext
    {
        /// <summary>
        /// Initializes a new instance of the ECommerceEntities class.
        /// Uses the connection string named "ECommerceEntities" from App.config.
        /// </summary>
        public ECommerceEntities()
            : base("name=ECommerceEntities")
        {
            // Disable lazy loading to prevent N+1 queries
            // Use Include() for eager loading when needed
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }

        /// <summary>
        /// Initializes a new instance with a custom connection string.
        /// </summary>
        /// <param name="connectionString">The database connection string</param>
        public ECommerceEntities(string connectionString)
            : base(connectionString)
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }

        // DbSets for all entities
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<SupportTicket> SupportTickets { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }

        /// <summary>
        /// Configures the model relationships and constraints.
        /// </summary>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // Remove pluralization convention
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

            // Configure User entity
            modelBuilder.Entity<User>()
                .HasKey(u => u.UserID);

            modelBuilder.Entity<User>()
                .Property(u => u.Username)
                .IsRequired()
                .HasMaxLength(50);

            modelBuilder.Entity<User>()
                .Property(u => u.Email)
                .IsRequired()
                .HasMaxLength(100);

            modelBuilder.Entity<User>()
                .Property(u => u.HashedPassword)
                .IsRequired()
                .HasMaxLength(255);

            modelBuilder.Entity<User>()
                .Property(u => u.UserRole)
                .IsRequired()
                .HasMaxLength(20);

            // Configure Category entity
            modelBuilder.Entity<Category>()
                .HasKey(c => c.CategoryID);

            modelBuilder.Entity<Category>()
                .Property(c => c.CategoryName)
                .IsRequired()
                .HasMaxLength(100);

            // Configure Product entity
            modelBuilder.Entity<Product>()
                .HasKey(p => p.ProductID);

            modelBuilder.Entity<Product>()
                .Property(p => p.ProductName)
                .IsRequired()
                .HasMaxLength(200);

            modelBuilder.Entity<Product>()
                .Property(p => p.Price)
                .HasPrecision(18, 2);

            modelBuilder.Entity<Product>()
                .HasRequired(p => p.Category)
                .WithMany(c => c.Products)
                .HasForeignKey(p => p.CategoryID);

            modelBuilder.Entity<Product>()
                .HasRequired(p => p.StoreOwner)
                .WithMany(u => u.Products)
                .HasForeignKey(p => p.StoreOwnerID);

            // Configure Inventory entity
            modelBuilder.Entity<Inventory>()
                .HasKey(i => i.InventoryID);

            modelBuilder.Entity<Inventory>()
                .HasRequired(i => i.Product)
                .WithOptional(p => p.Inventory);

            // Configure Order entity
            modelBuilder.Entity<Order>()
                .HasKey(o => o.OrderID);

            modelBuilder.Entity<Order>()
                .Property(o => o.TotalAmount)
                .HasPrecision(18, 2);

            modelBuilder.Entity<Order>()
                .Property(o => o.OrderStatus)
                .IsRequired()
                .HasMaxLength(20);

            modelBuilder.Entity<Order>()
                .HasRequired(o => o.Customer)
                .WithMany(u => u.Orders)
                .HasForeignKey(o => o.CustomerID);

            // Configure OrderDetail entity
            modelBuilder.Entity<OrderDetail>()
                .HasKey(od => od.OrderDetailID);

            modelBuilder.Entity<OrderDetail>()
                .Property(od => od.UnitPrice)
                .HasPrecision(18, 2);

            modelBuilder.Entity<OrderDetail>()
                .HasRequired(od => od.Order)
                .WithMany(o => o.OrderDetails)
                .HasForeignKey(od => od.OrderID)
                .WillCascadeOnDelete(true);

            modelBuilder.Entity<OrderDetail>()
                .HasRequired(od => od.Product)
                .WithMany(p => p.OrderDetails)
                .HasForeignKey(od => od.ProductID)
                .WillCascadeOnDelete(false);

            // Configure SupportTicket entity
            modelBuilder.Entity<SupportTicket>()
                .HasKey(st => st.TicketID);

            modelBuilder.Entity<SupportTicket>()
                .Property(st => st.Subject)
                .IsRequired()
                .HasMaxLength(200);

            modelBuilder.Entity<SupportTicket>()
                .Property(st => st.Status)
                .IsRequired()
                .HasMaxLength(20);

            modelBuilder.Entity<SupportTicket>()
                .Property(st => st.Priority)
                .IsRequired()
                .HasMaxLength(20);

            modelBuilder.Entity<SupportTicket>()
                .HasRequired(st => st.Customer)
                .WithMany(u => u.CustomerTickets)
                .HasForeignKey(st => st.CustomerID)
                .WillCascadeOnDelete(false);

            modelBuilder.Entity<SupportTicket>()
                .HasOptional(st => st.AssignedTo)
                .WithMany(u => u.AssignedTickets)
                .HasForeignKey(st => st.AssignedToID)
                .WillCascadeOnDelete(false);

            // Configure Review entity
            modelBuilder.Entity<Review>()
                .HasKey(r => r.ReviewID);

            modelBuilder.Entity<Review>()
                .HasRequired(r => r.Product)
                .WithMany(p => p.Reviews)
                .HasForeignKey(r => r.ProductID)
                .WillCascadeOnDelete(true);

            modelBuilder.Entity<Review>()
                .HasRequired(r => r.Customer)
                .WithMany(u => u.Reviews)
                .HasForeignKey(r => r.CustomerID)
                .WillCascadeOnDelete(false);

            base.OnModelCreating(modelBuilder);
        }
    }
}
