//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    /// <summary>
    /// ECommerceEntities - DbContext generated from EDMX (DB First Approach)
    /// Conform Curs 10 - ADO.NET Entity Framework
    /// </summary>
    public partial class ECommerceEntities : DbContext
    {
        /// <summary>
        /// Constructor using connection string from App.config
        /// Connection string name: ECommerceEntities
        /// </summary>
        public ECommerceEntities()
            : base("name=ECommerceEntities")
        {
            // Disable lazy loading (explicit Include() required) - Curs 10, pag. 12
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }

        /// <summary>
        /// Allows creation with custom connection string
        /// </summary>
        public ECommerceEntities(string connectionString)
            : base(connectionString)
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        // =====================================================
        // DbSet Properties - Conform Curs 10, pag. 6-8
        // =====================================================
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<SupportTicket> SupportTickets { get; set; }
        public virtual DbSet<TicketMessage> TicketMessages { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<StoreSetting> StoreSettings { get; set; }

        // =====================================================
        // Function Imports - Stored Procedures (Curs 10, pag. 13-14)
        // =====================================================

        /// <summary>
        /// GetLowStockProducts - Returns products with stock below minimum threshold
        /// </summary>
        public virtual ObjectResult<LowStockProduct> GetLowStockProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LowStockProduct>("GetLowStockProducts");
        }

        /// <summary>
        /// GetSalesStatistics - Returns sales statistics for a date range
        /// </summary>
        public virtual ObjectResult<SalesStatistics> GetSalesStatistics(DateTime? startDate, DateTime? endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(DateTime));

            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(DateTime));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalesStatistics>("GetSalesStatistics", startDateParameter, endDateParameter);
        }

        /// <summary>
        /// GetPopularProducts - Returns top selling products
        /// </summary>
        public virtual ObjectResult<PopularProduct> GetPopularProducts(int? topCount)
        {
            var topCountParameter = topCount.HasValue ?
                new ObjectParameter("TopCount", topCount) :
                new ObjectParameter("TopCount", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PopularProduct>("GetPopularProducts", topCountParameter);
        }

        /// <summary>
        /// GetCustomerOrderHistory - Returns order history for a customer
        /// </summary>
        public virtual ObjectResult<CustomerOrderHistory> GetCustomerOrderHistory(int? customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustomerOrderHistory>("GetCustomerOrderHistory", customerIDParameter);
        }

        /// <summary>
        /// GetDashboardStatistics - Returns dashboard statistics
        /// </summary>
        public virtual ObjectResult<DashboardStatistics> GetDashboardStatistics()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DashboardStatistics>("GetDashboardStatistics");
        }
    }

    // =====================================================
    // Complex Types for Stored Procedure Results
    // =====================================================

    /// <summary>
    /// Result type for GetLowStockProducts stored procedure
    /// </summary>
    public partial class LowStockProduct
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public int StockQuantity { get; set; }
        public int MinimumStock { get; set; }
        public string CategoryName { get; set; }
        public int? StockNeeded { get; set; }
    }

    /// <summary>
    /// Result type for GetSalesStatistics stored procedure
    /// </summary>
    public partial class SalesStatistics
    {
        public int? TotalOrders { get; set; }
        public decimal? TotalRevenue { get; set; }
        public decimal? AverageOrderValue { get; set; }
        public int? UniqueCustomers { get; set; }
        public int? ProductsSold { get; set; }
    }

    /// <summary>
    /// Result type for GetPopularProducts stored procedure
    /// </summary>
    public partial class PopularProduct
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public string CategoryName { get; set; }
        public int? OrderCount { get; set; }
        public int? TotalQuantitySold { get; set; }
        public decimal? TotalRevenue { get; set; }
        public double? AverageRating { get; set; }
        public int? ReviewCount { get; set; }
    }

    /// <summary>
    /// Result type for GetCustomerOrderHistory stored procedure
    /// </summary>
    public partial class CustomerOrderHistory
    {
        public int OrderID { get; set; }
        public DateTime OrderDate { get; set; }
        public decimal TotalAmount { get; set; }
        public string OrderStatus { get; set; }
        public string ShippingAddress { get; set; }
        public string PaymentMethod { get; set; }
        public int? ItemCount { get; set; }
    }

    /// <summary>
    /// Result type for GetDashboardStatistics stored procedure
    /// </summary>
    public partial class DashboardStatistics
    {
        public int? TotalCustomers { get; set; }
        public int? TotalStoreOwners { get; set; }
        public int? TotalSupportAgents { get; set; }
        public int? TotalProducts { get; set; }
        public int? PendingOrders { get; set; }
        public int? OpenTickets { get; set; }
        public decimal? MonthlyRevenue { get; set; }
        public int? LowStockProducts { get; set; }
    }
}
